### ISSUE TITLE
utils.TestServer.close(): unexpected keyword argument

### ISSUE THREAD

**Issue by garyo** [yunstanford/pytest-sanic#17]
In pytest_sanic.utils.TestServer.close(), there is this code:

```
            # Force close connections
            coros = []
            for conn in self.connections:
                if hasattr(conn, "websocket") and conn.websocket:
>                   coros.append(conn.websocket.close_connection(after_handshake=False))
E                   TypeError: close_connection() got an unexpected keyword argument 'after_handshake'
```
As you can see from the `E` error here, conn.websocket.close_connection() doesn't expect an after_handshake arg.

**Comment by yunstanford** [comment]
@garyo Thanks for bringing up this. looks like because of incompatible change in `websockets`, they've bumped up version to 5.0 recently.

Also we also have to fix Sanic here, https://github.com/channelcat/sanic/blob/master/sanic/server.py#L668, I'll fix both soon.

To quick unblock yourself, you can use `websockets < 5.0`

**Comment by garyo** [comment]
Actually I just locally edited utils.py 😄 and removed the extra arg. Thanks for the quick response!

**Comment by garyo** [comment]
Sanic is now updated to require websockets 5.0, so this failure is is back.

**Comment by yunstanford** [comment]
Yeah, but Sanic didn't release the latest version to pypi.  Anyway, I guess I can push a fix for both case.

**Comment by yunstanford** [comment]
ok, fixed.
